#!/bin/sh

home=/work/halla/triton/Bane/Tri_offline/ped_scan/gen_job
image_dir=/work/halla/triton/Bane/Tri_offline/ped_scan/det
out_dir=/work/halla/triton/Bane/Tri_offline/ped_scan/ped_table
list_dir=/work/halla/triton/Bane/Tri_offline/
#
# Function to check if input is an integer
#

run=$1
#kin=$2
#
    if ! [ -d batch_files ]
	then 
	echo "----------------------------------------------------------------"
	echo "I need batch_files directory. I am going to create it"
	echo  
	mkdir batch_files
    fi
    
	INPUT=/mss/halla/triton/prod/pass1_calibration
	kin=$(root -b -l -n -q "which_kin.C(${run})")
	echo "${kin}" >tmp.tmp
	FN="tmp.tmp"
	tmplin=$(cat "tmp.tmp")
	KIN=${tmplin#*(int)}
	echo ${KIN}
	
	if [ ${KIN} -eq -1 ] 
	then
		echo "Run not found in runlist, exiting"
		exit
	fi
#
#
    	rm -f ./batch_files/batch_${batch_run}*
	
	rm -f ./batch_corrections/batch_outfiles/${run}.out
    	echo "#!/bin/sh" >> batch_files/batch_${run}
    	echo "export ANALYZER=/work/halla/triton/MARATHON_Replay/analyzer1.6" >>batch_files/batch_${run}
	echo "export PATH=\${ROOTSYS}/bin:\${ANALYZER}:\${PATH}" >>batch_files/batch_${run}
   	echo "cd ${list_dir}/ped_scan" >>batch_files/batch_${run}
    	echo " ">>batch_files/batch_${run}
   	echo "analyzer -b -q -l -n .x '/work/halla/triton/Bane/Tri_offline/ped_scan/batch_ped_scan.C(${run})'>>./batch_corrections/batch_outfiles/${run}.out" >>batch_files/batch_${run}
  
    	chmod +x batch_files/batch_${run}
    

	echo "batch_files/batch_"${run}" has been created!"
   	echo " "
	
	Arm=""    
	p1=""
	p2=""
	if (( run < 90000 ))	
	then 
		Arm="L."
		p1="prl1."
		p2="prl2."
	else
		
		Arm="R."
		p1="ps."
		p2="sh."
	fi
# Write the jsub script
#

    rm -f batch_files/jscript_${run}*
    echo "PROJECT     triton" > batch_files/jscript_${run}
    echo "COMMAND     ${home}/batch_files/batch_"${run} >>batch_files/jscript_${run}
    echo "JOBNAME     H3_ped_scan_"${run}>>batch_files/jscript_${run}
    echo "TRACK       debug" >> batch_files/jscript_${run}
    echo "TIME        10" >>batch_files/jscript_${run}
    echo "MEMORY      1000 MB" >>batch_files/jscript_${run}
    echo "OS          centos7" >>batch_files/jscript_${run}
    echo "INPUT_FILES: ${INPUT}/kin${KIN}/tritium_${run}_*.root" >>batch_files/jscript_${run}
    
    echo "OUTPUT_DATA: Pedestals_${Arm}s0.la_${run}.pdf">>batch_files/jscript_${run}
    echo "OUTPUT_TEMPLATE: ${image_dir}/Pedestals_${Arm}s0.la_${run}.pdf">>batch_files/jscript_${run}

    echo "OUTPUT_DATA: Pedestals_${Arm}s0.ra_${run}.pdf">>batch_files/jscript_${run}
    echo "OUTPUT_TEMPLATE: ${image_dir}/Pedestals_${Arm}s0.ra_${run}.pdf">>batch_files/jscript_${run}
    
    echo "OUTPUT_DATA: Pedestals_${Arm}s2.la_${run}.pdf">>batch_files/jscript_${run}
    echo "OUTPUT_TEMPLATE: ${image_dir}/Pedestals_${Arm}s2.la_${run}.pdf">>batch_files/jscript_${run}
    
    echo "OUTPUT_DATA: Pedestals_${Arm}s2.ra_${run}.pdf">>batch_files/jscript_${run}
    echo "OUTPUT_TEMPLATE: ${image_dir}/Pedestals_${Arm}s2.ra_${run}.pdf">>batch_files/jscript_${run}
    
    echo "OUTPUT_DATA: Pedestals_${Arm}${p1}a_${run}.pdf">>batch_files/jscript_${run}
    echo "OUTPUT_TEMPLATE: ${image_dir}/Pedestals_${Arm}${p1}.a_${run}.pdf">>batch_files/jscript_${run}
    
    echo "OUTPUT_DATA: Pedestals_${Arm}${p2}a_${run}.pdf">>batch_files/jscript_${run}
    echo "OUTPUT_TEMPLATE: ${image_dir}/Pedestals_${Arm}${p2}.a_${run}.pdf">>batch_files/jscript_${run}
    
    echo "OUTPUT_DATA: Pedestals_${Arm}cer.a_${run}.pdf">>batch_files/jscript_${run}
    echo "OUTPUT_TEMPLATE: ${image_dir}/Pedestals_${Arm}cer.a_${run}.pdf">>batch_files/jscript_${run}
   
    echo "OUTPUT_DATA: ${run}.csv">>batch_files/jscript_${run}
    echo "OUTPUT_TEMPLATE: ${out_dir}/${run}.csv">>batch_files/jscript_${run}
 
    echo "SINGLE_JOB: true" >>batch_files/jscript_${run}
	   
    echo "batch_files/jscript_"${run}" has been created."
    echo " " 
    echo "Now, let us wait for the farms..."
    echo " "
################################
#    Submit job to the farm    #  
################################
#   swif add-jsub -workflow h3_ped_scan -create -script ./batch_files/jscript_${run}
################################
################################

    echo "Job "${run} "has been submited to workflow h3_ped_scan!"
    echo
    echo
#
    

echo
echo "***** Good Bye and thank you for using the script *****"
echo
